# 定义一个名为 Pages 的动作
name: HexoCI
 
# 当有一个新的推送（push）到名为 hexo 的分支时，执行部署任务
on:
  push:
    branches:
      - Hexo
 
# 定义一个名为 build-and-deploy 的 job
jobs:
  build-and-deploy:
    # 运行在最新版本的 Ubuntu 操作系统
    runs-on: ubuntu-latest

    # 定义一个名为 build 的步骤
    steps:
      # 检查出仓库的代码
      - name: Checkout
        uses: actions/checkout@v2

      # 安装 Node.js 和 npm
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # 安装 Hexo 依赖
      - name: Install Hexo
        run: |
          npm install hexo-cli -g
          npm install

      # 生成静态文件
      - name: Generate
        run: hexo generate

      # 部署到 GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          branch: main
          
